version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3030:3000"
    volumes:
      - ./nextjs-app:/app
    working_dir: /app
    command: npm run dev
