version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
    working_dir: /app
    command: npm start
    restart: always

volume:
  react-app: