# Node.jsをベースにする
FROM node:16

# 必要なパッケージをインストール
RUN npm install -g create-react-app

# アプリケーションディレクトリを作成
WORKDIR /app

# 依存関係をインストール
COPY ./react-app/package.json ./react-app/package-lock.json ./
RUN npm install

# アプリケーションのソースをコピー
COPY ./react-app ./
