# Pythonをベースにする
FROM python:3.9-slim

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y libmariadb-dev

# FlaskとMariaDBのPythonドライバをインストール
RUN pip install Flask Flask-SQLAlchemy pymysql

# アプリケーションディレクトリを作成
WORKDIR /app

# アプリケーションのソースをコピー
COPY ./flask-app /app
